spring:
   datasource:
      url: jdbc:mysql://stockprices.c5avsl1h7ppv.ap-northeast-1.rds.amazonaws.com:3306/stockprices
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root1234
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            
server:
  port: 9090